### ISSUE TITLE
Locate GC log file folder

### ISSUE THREAD

**Issue by shawark** [instaclustr/supportCenter#28]
https://github.com/instaclustr/supportCenter/blob/6809402339f6cfbe0cb6daca22b227a2ddf9825f/agent/collector/node.go#L196
The code assumes GC log file is retrieved from `home-path/logs` folder. 

Few things:
* `home-path` is not very descriptive that links to gc log. Users may think the `home-path` is their SSH user home rather than the Cassandra home. Probably need to be documented in Readme (actually better to document all parameters of settings.yaml)
* `ccm` by default store gc logs under `.ccm/test/<node name>/logs` whereas our clusters store under `/var/lib/cassandra`. I have not tested other platforms, but presumably, customer can set whatever in `-Xloggc` so makes sense  to have `GC-path` as a separate parameter

**Comment by mrlika** [comment]
Is `gc-path` fine to be consistent with other parameters?

```yaml
# Collecting settings
node:
  cassandra:
    config-path: "/etc/cassandra"
    log-path: "/var/log/cassandra"
    gc-path: "/var/lib/cassandra"
    data-path:
      - "/var/lib/cassandra/data"
```
